
postgres:
  host: db # according to the service name in docker-compose
  port: ${oc.env:POSTGRES_PORT}
  user: ${oc.env:POSTGRES_USER}
  password: ${oc.env:POSTGRES_PASSWORD}
  db: ${oc.env:POSTGRES_DB}