# main configs

# default hydra configuration
defaults:
  - _self_
  - api: [default]
  - database: [postgres]
  - detector: [faceonnx]
  - recognizer: [arcface, recognizer]
  - logger: [default] 
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

# override hydra output directory
hydra:
  run:
    dir: .
  output_subdir: null

# override logger level
logger:
  level: INFO

# service mode
service: api